org.gradle.jvmargs=-Xmx3G -Dfile.encoding=UTF-8 -Duser.country=US -Duser.language=en -Duser.variant
minecraft_version=1.20.1
minecraft_version_range=[1.20.1,1.21)
forge_version=47.1.0
forge_version_range=[47,1.21)
loader_version_range=[47,)
mod_id=edge_glow
mod_name=Edge Glow
mod_license=All Rights Reserved
mod_version=1.0.0
mod_group_id=net.jules.edge_glow
mod_authors=Jules
mod_description=Adds edge glow effects to held items.
