name: Build Edge Glow

on: [push, pull_request]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Set up JDK 17
        uses: actions/setup-java@v3
        with:
          java-version: '17'
          distribution: 'temurin'
      - name: Grant execute permission for gradlew
        run: chmod +x gradlew
      - name: Build with Gradle
        run: ./gradlew build
      - name: Bundle Artifacts
        run: |
          mkdir release_artifacts
          cp build/libs/*.jar release_artifacts/
          cd example_pack && zip -r ../release_artifacts/example_resource_pack.zip . && cd ..
      - name: Upload Artifact
        uses: actions/upload-artifact@v4
        with:
          name: edge-glow-release
          path: release_artifacts/
